version: '3'

services:
  postgres-kk:
    image: postgres:15
    container_name: postgres-kk
    volumes:
      - postgres_data_kk:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: keycloakuser
      POSTGRES_PASSWORD: keycloakpass
    networks:
      - keycloak-network

  keycloak-web:
    build:
      context: .
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak-web
    ports:
      - 8180:8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres-kk
      DB_SCHEMA: public
      DB_DATABASE: keycloakdb
      DB_USER: keycloakuser
      DB_PASSWORD: keycloakpass
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/import/realm-export.json:/opt/keycloak/data/import/realm-export.json
      - ./keycloak/providers/travel-assistant-0.0.1-SNAPSHOT.jar:/opt/keycloak/providers/travel-assistant-0.0.1-SNAPSHOT.jar
    depends_on:
      - postgres-kk
    networks:
      - keycloak-network
    command: ["start-dev", "--import-realm"]

networks:
  keycloak-network:
    driver: bridge

volumes:
  postgres_data_kk:
    driver: local
